---
functional:
  - на сайте должна быть реализована возможность представить двум игрокам возможность соревноваться друг с другом в решении задач и видеть написание кода друг у друга
  - на сайте должны отображаться рейтинги, игра с ботом, игра с другом по ссылке
non-functional:
  - сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - сайт должен быть безопасным и защищать данные пользователя
  - сайт должен быть удобным на мобильном устройстве
  - сайт должен быть протестирован на совместимость с последними версиями браузеров
  - сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - сайт должен быть оформлен в спокойных тонах, с возможностью менять цветовые решения пользователем
  - сайт должен в режиме реального времени показывать пользователю код его соперника
